version: "3.9"
services:
  app:
    container_name: django
    build: .

    ports:
      - "8000:8000"
    tty: true
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    tty: true
    volumes:
      - db_django:/var/lib/mysql

volumes:
  db_django:
